### PR TITLE
Fix error caused by "-mfloat-hard" option

### PR DESCRIPTION
**Pull request by bandvig**
Fix internal compiler error occurrence when building with "-mfloat-hard" option. The error was discussed here  http://juliusbaxter.net/openrisc-irc/%23openrisc.2016-07-02.log.html

### CODE REVIEW

**Comment by bandvig** [comment]
I see the Travis CI failed to build, however there aren't problems with sources. Travis reported "The job exceeded the maximum time limit for jobs, and has been terminated." 
https://travis-ci.org/openrisc/newlib/jobs/447123909

**Comment by wallento** [comment]
Thanks for working on it. I have restarted the travis build, just to be sure, but lgtm

**Comment by stffrdhrn** [comment]
Is this still an issue?

**Comment by stffrdhrn** [comment]
Hi @bandvig is this still an issue?

**Comment by bandvig** [comment]
@stffrdhrn 
If I remember correctly it was an issue due to absence of unordered comparison (or something like this). Any way I don't see such problems with actual versions of GCC, NewLIB and FPU.

**Pull request closed without merging**
